spring:
  application:
    name: altech-electronic-store
  datasource:
    url: jdbc:h2:mem:electronicstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

jwt:
  secret: your-256-bit-secret-key-here-1234567890abcdef1234567890abcdef
  expiration: 86400000 # 24 hours in milliseconds
    