server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:h2:mem:electronicstore;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
app:
  security:
    jwt:
      secret-key: "your-256-bit-secret-key-here-1234567890abcdef1234567890abcdef"
      expiration: 86400000 # 24 hours in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds